# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# WEB #####################################################
# #########################################################
  web:
    container_name: digitec_web_local
    volumes:
      - ./web:/app:cached
      - /app/node_modules
    working_dir: /app
    command: sh -lc "pnpm install && pnpm dev"
    environment:
      CI: "true"
      PNPM_CONFIG_CONFIRM_MODULES_PURGE: "false"
      DATABASE_URL: "postgresql://digitec:changeme@db:5432/digitec?schema=public"
      NODE_ENV: development
      PORT: "3002"
    ports:
      - "3002:3002"

# #########################################################
# DB ######################################################
# #########################################################
  db:
    container_name: digitec_db_local
    ports:
      - "5432:5432"

# =========================================================
# Networks ================================================
# =========================================================


# =========================================================
# Volumes =================================================
# =========================================================

