# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# WEB #####################################################
# #########################################################
  web:
    container_name: digitec_web_prod
    image: yourdockerhubuser/digitec_web:latest
    environment:
      DATABASE_URL: "postgresql://digitec:changeme@db:5432/digitec?schema=public"
      NODE_ENV: production
      PORT: "3002"
    ports:
      - "3002:3002"
    restart: unless-stopped

# #########################################################
# DB ######################################################
# #########################################################
  db:
    container_name: digitec_db_prod
    image: postgres:15
    environment:
      POSTGRES_USER: digitec
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: digitec
    volumes:
      - db-data:/var/lib/postgresql/data

# =========================================================
# Networks ================================================
# =========================================================


# =========================================================
# Volumes =================================================
# =========================================================
volumes:
  db-data:
