services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: digitec_web
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3002
    ports:
      - 3002:3002
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: digitec_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    # Uncomment to access DB from host:
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb
    container_name: digitec_pgweb
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGWEB_DATABASE_URL: ${DATABASE_URL}?sslmode=disable
    ports:
      - 8089:8081

volumes:
  db-data: