services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hello
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

volumes:
  db-data:
